### ISSUE TITLE
How to setup rust and cargo for project

### ISSUE THREAD

**Issue by santhosh-D-subramani** [mdddj/android_adb_tool#1]
if build for windows i get this error
```
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
  SEVERE: error[E0433]: failed to resolve: could not find `unix` in `os`
  SEVERE: error[E0432]: unresolved import `libc::pid_t`
  SEVERE: error[E0432]: unresolved import `os::target`
  SEVERE: error[E0432]: unresolved import `os::target`
  SEVERE: error[E0432]: unresolved import `os::target`
  SEVERE: error[E0432]: unresolved import `os::target`
  SEVERE: error[E0432]: unresolved import `os::target`
  SEVERE: error[E0432]: unresolved import `os::target`
  SEVERE: error[E0432]: unresolved import `os::target`
  SEVERE: error[E0432]: unresolved import `os::target`
  SEVERE: error[E0432]: unresolved import `os::target`
  SEVERE: error[E0432]: unresolved import `libc::pid_t`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0433]: failed to resolve: could not find `target` in `os`
  SEVERE: error[E0599]: no method named `inner` found for reference `&Termios` in the current scope
  SEVERE: error[E0599]: no method named `inner_mut` found for mutable reference `&mut Termios` in the current scope
  SEVERE: error[E0599]: no method named `inner` found for reference `&Termios` in the current scope
  SEVERE: error[E0599]: no method named `inner` found for reference `&Termios` in the current scope
  SEVERE: error[E0599]: no method named `inner_mut` found for mutable reference `&mut Termios` in the current scope
  SEVERE: error[E0599]: no method named `inner_mut` found for mutable reference `&mut Termios` in the current scope
  SEVERE: error[E0599]: no method named `inner_mut` found for mutable reference `&mut Termios` in the current scope
  SEVERE: error[E0599]: no method named `inner_mut` found for mutable reference `&mut Termios` in the current scope
  SEVERE: error[E0599]: no method named `inner_mut` found for mutable reference `&mut Termios` in the current scope
  SEVERE: error[E0599]: no method named `inner` found for reference `&Termios` in the current scope
SEVERE : error : could not compile `termios` (lib) due to 41 previous errors [C:\Users\hfmmb\StudioProjects\adb_test2\build\windows\x64\plugins\android_adb_tool\android_adb_tool_cargokit.vcxproj]
SEVERE : warning : build failed, waiting for other jobs to finish... [C:\Users\hfmmb\StudioProjects\adb_test2\build\windows\x64\plugins\android_adb_tool\android_adb_tool_cargokit.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'C:\Users\hfmmb\StudioProjects\adb_test2\build\windows\x64\CMakeFiles\74b773c72543594e6092d9db9bb2f7b6\android_adb_tool.dll.rule;C:\Users\hfmmb\StudioProjects\adb_test2\build\windows\x64\CMakeFiles\0e3777458c9c9537aa5f3e6ddc4bcccb\android_adb_tool_cargokit.rule' exited with code -1. [C:\Users\hfmmb\StudioProjects\adb_test2\build\windows\x64\plugins\android_adb_tool\android_adb_tool_cargokit.vcxproj]
Error: Build process failed.
```
in android after clicking adb connect :- 
```
E/flutter ( 7918): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PanicException(called `Result::unwrap()` on an `Err` value: IOError(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))
E/flutter ( 7918): #0      SimpleDecoder.decode (package:flutter_rust_bridge/src/codec/base.dart:35:9)
E/flutter ( 7918): #1      SseCodec._decode (package:flutter_rust_bridge/src/codec/sse.dart:42:55)
E/flutter ( 7918): #2      SseCodec.decodeObject (package:flutter_rust_bridge/src/codec/sse.dart:32:12)
E/flutter ( 7918): <asynchronous suspension>
E/flutter ( 7918): #3      _MyHomePageState._connect (package:adb_test2/main.dart:128:18)
E/flutter ( 7918): <asynchronous suspension>
E/flutter ( 7918): 
```
In pub.dev there isnt any steps to setup rust/cargo for project.

**Comment by mdddj** [comment]
Sorry, I don't have a Windows platform for testing. On the Android side, trying to connect using address 10.0.2.2 requires enabling WiFi network access permissions
```xml
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
```
<img width="490" alt="image" src="https://github.com/mdddj/android_adb_tool/assets/29020213/f40040eb-5810-4279-8b0e-d8152d5f8f06">

**Comment by santhosh-D-subramani** [comment]
now its working 👍
