### ISSUE TITLE
build error - SEVERE: Cargokit BuildTool failed 

### ISSUE THREAD

**Issue by santhosh-D-subramani** [mdddj/android_adb_tool#3]
Im getting this build error in my new project, and there is no error if i run Flutter run in  your example app from github( yet same error popsup if i run Flutter build apk ).

```
Running Gradle task 'assembleRelease'...                        
INFO: Precompiled binaries are disabled
INFO: Installing Rust target: armv7-linux-androideabi
INFO: Building android_adb_tool for armv7-linux-androideabi
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: External Command: rustup "run" "stable" "cargo" "build" "--manifest-path" "C:\Users\hfmmb\AppData\Local\Pub\Cache\hosted\pub.dev\android_adb_tool-0.0.2\rust\Cargo.toml" "-p" "android_adb_tool" "--release" "--target" "armv7-linux-androideabi" "--target-dir" "C:\Users\hfmmb\StudioProjects\adb_test2\build\android_adb_tool/build"
SEVERE: Returned Exit Code: 101
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDOUT:
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDERR:
SEVERE: Compiling proc-macro2 v1.0.82
SEVERE:    Compiling libc v0.2.154
SEVERE:    Compiling unicode-ident v1.0.12
SEVERE:    Compiling memchr v2.7.2
SEVERE:    Compiling autocfg v1.3.0
SEVERE: error: linker `link.exe` not found
SEVERE:   |
SEVERE:   = note: program not found
SEVERE: 
SEVERE: note: the msvc targets depend on the msvc linker but `link.exe` was not found
SEVERE: 
SEVERE: note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.
SEVERE: 
SEVERE: note: VS Code is a different product, and is not sufficient.
SEVERE: 
SEVERE: error: could not compile `proc-macro2` (build script) due to 1 previous error
SEVERE: warning: build failed, waiting for other jobs to finish...
SEVERE: error: could not compile `libc` (build script) due to 1 previous error
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      runCommand (package:build_tool/src/util.dart:118:5)
SEVERE: #1      RustBuilder.build (package:build_tool/src/builder.dart:139:5)
SEVERE: <asynchronous suspension>
SEVERE: #2      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:68:25)
SEVERE: <asynchronous suspension>
SEVERE: #3      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
SEVERE: <asynchronous suspension>
SEVERE: #4      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
SEVERE: <asynchronous suspension>
SEVERE: #5      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
SEVERE: <asynchronous suspension>
SEVERE: #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #7      runMain (package:build_tool/src/build_tool.dart:248:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================
```

**Comment by mdddj** [comment]
Fixed in version 1.0.0
<img width="986" alt="image" src="https://github.com/mdddj/android_adb_tool/assets/29020213/f438618f-c876-476a-9d33-49e364f12a16">
